### ISSUE TITLE
Fix API Internal server error for forbidden refresh token

### ISSUE THREAD

**Issue by carlobortolan** [Embloy/Embloy-Backend#71]
When sending a POST request to `api/v0/auth/token/refresh` to create a new refresh token for a _unverified_ user, the API returns:

```
{
    "error":"Internal Server Error",
    "status":500
}
```

instead of e.g.: 
```
{
  "user": [
    {
      "error": "ERR_RAC",
      "description": "Proceeding is inhibited by an access restriction"
    }
  ]
}
```

Server logs:
```
Aug 16 04:18:48 PM  [a28874ee-212c-4a92-8b3f-0b2155472211] app/controllers/api/v0/authentications_controller.rb:15:in `create_refresh'
```

**Comment by carlobortolan** [comment]
Solved by handling uncaught exception in `api_exception_handler`:

```
CustomExceptions::InvalidUser::Inactive (CustomExceptions::InvalidUser::Inactive):

app/service/authentication_token_service.rb:86:in `call'
app/controllers/api/v0/authentications_controller.rb:15:in `create_refresh'
```
